### ISSUE TITLE
Tool isn't working appropriately on many popular websites

### ISSUE THREAD

**Issue by rdbcasillas** [GitMurf/roam-highlighter#29]
Hello,

Thanks a lot for making this. I am not sure what's the right place to post the popular websites where the tools isn't working as expected. But here are a couple of sites that I go to regularly: 

http://www.paulgraham.com
https://numinous.productions/ttft/

As can be seen on these sites, the tool makes each line as a new bullet. Looking at chrome inspector, I do understand that the pages are structured in a weird way which is breaking the tool and maybe you are already working on fixing these outliers. 

Apologies if this isn't the right place to post this issue.

**Comment by GitMurf** [comment]
@rdbcasillas Thank you very much for your feedback! This is exactly the right place to report issues/questions. Also if you have any new ideas or requests for new features, this is also the place. I will look into your comments above and get back to you on it.

**Comment by GitMurf** [comment]
@rdbcasillas are you referring to the extra line breaks it is creating in the middle of sentences? That is definitely an issue with the website as they are arbitrarily trying to make their text width shorter by using line breaks instead of managing with CSS / Styling. That being said, my Highlighter extension has settings to handle those peculiar situations. Please see the following GIFs I will be posting below and let me know if that solves your problems?

**Comment by GitMurf** [comment]
![troubleshooting line break issues](https://user-images.githubusercontent.com/64155612/83104141-fd9c1c00-a06c-11ea-8e87-f8a9eaed73a8.gif)

**Comment by GitMurf** [comment]
![troubleshooting line break issues pt2](https://user-images.githubusercontent.com/64155612/83108937-6091b100-a075-11ea-8c80-531c091f68ac.gif)

**Comment by rdbcasillas** [comment]
Thank you! This works very well for me. Should have fully explored the settings.

**Comment by GitMurf** [comment]
@rdbcasillas awesome! Glad it worked out. These kinds of scenarios are exactly why I worked those settings/options in there :) If you run into any other issues don't hesitate to reach out. As you can see, I am pretty responsive to Github Issues raised.
