### ISSUE TITLE
Settings aren't saved

### ISSUE THREAD

**Issue by arthurjosse** [GitMurf/roam-highlighter#34]
Roam-highlighter v. 1.9.7.1
Tested in Firefox v. 76 and Chrome v. 85

1. In a tab, Roam-highlighter panel expanded
2. Settings set to Obsidian
3. Hit save
4. Close browser
5. Reboot and go back to the same tab
6. Roam-highlighter has gone back to Roam as its default setting

**Comment by GitMurf** [comment]
@arthurjosse i know it’s confusing but for the default settings chooser you need to click “SET” to use those settings. I have changed that all together now and update should be out shortly. Just waiting for chrome store review. Now it will save “onChange” event so as soon as you switch drop down from Roam to obsidian it will save. Also the save button is now greyed out unless there is something to save in which case it turns blue until you click it.

Does that all make sense?

**Comment by arthurjosse** [comment]
Thanks for your responsiveness and yes it completely makes sense.

I was already clicking on the "set" button but I think it worked as intended: resetting to default settings. It was a misunderstanding from my part.

But still, I have just tested the extension v. 1.9.7.2 in Chrome and it seems that not all settings are saved. The line breaks handling is saved but not the way the clipboard is showed. And we can tick both plain text and HTML, or left the two boxes unchecked. Shouldn't they be mutually exclusive? Shouldn't one of them be required? Also, a quick remark: although my monitor is crappy, I can barely see the text placeholders and my inputs have the same style as the placeholders.

**Comment by GitMurf** [comment]
“it seems that not all settings are saved.”

Do you specifically mean the plain text and HTML settings? That does not save as the default should show plain text because it’s more human readable. To be honest I’m probably going to remove these items. They are more for me when testing to see what the HTML on clipboard looks like. 

“And we can tick both plain text and HTML, or left the two boxes unchecked. Shouldn't they be mutually exclusive? Shouldn't one of them be required?”

See my answer above. Does that help?

“Also, a quick remark: although my monitor is crappy, I can barely see the text placeholders and my inputs have the same style as the placeholders.”

This is great feedback. So are you saying it’s 1) it’s hard to read in general and 2) you can’t tell difference between placeholder text and actual inputted text and would like some more “contrast”/distinction between the two?

**Comment by arthurjosse** [comment]
OK, got it, my settings are saved. 

On my monitor I cannot see the placeholders if I don't lean over the screen. And yes there is no difference between the placeholders and the inputted text. Inputted values are greyed out. And some of the inputs are buggy: see the attached screenshot, the height input value style suddenly appeared, the caret is white and I can't highlight it (by holding down the left click). Can't say if "20%" is the placeholder or the value I've entered. Looks like they're overlaid.

**Comment by Quorafind** [comment]
@GitMurf A small question: I changed settings set from Roam Research to Obsidian, it will not be saved. Should I change it again and again when I use it to capture stuff?

**Comment by GitMurf** [comment]
Combined into Issue #50
