### ISSUE TITLE
Nothing happens on select in Firefox

### ISSUE THREAD

**Issue by jedweb** [GitMurf/roam-highlighter#51]
I'm on a page, I hit Alt-X (or click on the icon) to show the Roam Highlighter window. I select any text on the page. The text is not highlighted yellow like in the demos. Nothing shows up in the Roam Highlighter pane.

I copy the text. Still nothing. Is there more to this than I'm not aware of?

**Comment by agriffis** [comment]
@jedweb Are you, by chance, double- or triple-clicking to select? That doesn't work for me either. But if I do a simple drag to select, it works fine.

**Comment by jdoree** [comment]
@agriffis ... it seems to be working now. I'm not sure what changed. I hadn't tried again since posting. I'm not sure if it's a Firefox update, a Roam Highlighter update, or gremlins, but all is well now. 

Thanks for the response!

**Comment by agriffis** [comment]
No problem, I'm just another user. Feel free to close the issue, though, I'm sure @GitMurf would appreciate it.

**Comment by jdoree** [comment]
Good point. Will do.

**Comment by GitMurf** [comment]
@jdoree @jedweb maybe you are the same person? Probably don't have permission to close it because logged in as a different user?

Sorry for missing this original post. Glad it's working now! Although I haven't made any updates in several months so it wasn't something I fixed to make it work again ;)

**Comment by jedweb** [comment]
Thanks @GitMurf . All Good.
